name: Terraform Apply

on:
  push:
    branches:
      - main

env:
  aws_region: us-east-1
  terraform_version: 1.6.5
  terraform_directory: ./

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Find PR associated with the commit
        id: find_pr
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 100
            });

            const associatedPR = pr.data.find(p => p.merge_commit_sha === context.sha);

            if (associatedPR) {
              core.setOutput('pr_number', associatedPR.number);
            } else {
              throw new Error("No PR found for this commit.");
            }

      - name: Debug PR
        run: "echo 'PR Number: ${{ steps.find_pr.outputs.number }}'"

      - name: Terraform Apply
        uses: ./.github/apply
        with:
          terraform_version: ${{ env.terraform_version }}
          terraform_directory: ${{ env.terraform_directory }}
          pr_number: ${{ steps.find_pr.outputs.number }}
          aws_region: ${{ env.aws_region }}
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}